TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.2 
  
  max_vel_theta: 0.65
  min_in_place_vel_theta: 0.65
  
  escape_vel: -0.3 
  
  acc_lim_theta: 1.3
  acc_lim_x: 0.2
  acc_lim_y: 0.2 

  holonomic_robot: false
  vtheta_samples: 10 
  vx_samples: 4 

