TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1 
  max_vel_theta: 4.0

  min_in_place_vel_theta: 0.4 
  
  escape_vel: -0.3 
  
  acc_lim_theta: 3.2 
  acc_lim_x: 0.1 
  acc_lim_y: 0.1 

  holonomic_robot: false
  vtheta_samples: 10 
  vx_samples: 4 

