obstacle_range: 2.5
raytrace_range: 3.0

robot_radius: 0.2 # distance a circular robot should be clear of obstacle

inflation_radius: 0.2 

observation_sources: laser_scan_sensor #laser scan

laser_scan_sensor: {sensor_frame: scan,  data_type: LaserScan, topic: /scan, marking: true, clearing: true}


# refer to: http://wiki.ros.org/costmap_2d
# pay attention to first paragraph of section 8.1.4
