#static map true if using existing map

global_costmap:
	global_frame: /map 
	robot_base_frame: base_link
	update_frequency: 1.0
	publish_frequency: 1.0
	resolution: 0.05 #refer to hector or gmapping params 
	static_map: true
	width: 10.0  # dimensions of map in meters NEED TO BE SET
	height: 10.0
